export type IngredientExplanationEntry = {
  aliases: string[];
  id: string;
  name: string;
  plainEnglish: string;
  usedFor: string;
  whyItMatters: string;
};

export const mockIngredientExplanations: IngredientExplanationEntry[] = [
  {
    aliases: ['sugar', 'cane sugar', 'brown sugar'],
    id: 'sugar',
    name: 'Sugar',
    plainEnglish: 'This adds sweetness, but too much can make a product less balanced.',
    usedFor: 'Adds sweetness and improves taste.',
    whyItMatters: 'It can quickly raise how much sugar you eat in a day.',
  },
  {
    aliases: ['high fructose corn syrup', 'hfcs', 'fructose glucose syrup'],
    id: 'high-fructose-corn-syrup',
    name: 'High Fructose Corn Syrup',
    plainEnglish: 'This is a sweetener often used in highly processed foods.',
    usedFor: 'Adds sweetness at a low cost.',
    whyItMatters: 'It can be a sign the product leans heavily on added sugar.',
  },
  {
    aliases: ['aspartame', 'e951'],
    id: 'aspartame',
    name: 'Aspartame',
    plainEnglish: 'This is a low-calorie sweetener used instead of sugar.',
    usedFor: 'Keeps products sweet without adding much sugar.',
    whyItMatters: 'Some people prefer to limit artificial sweeteners or avoid them entirely.',
  },
  {
    aliases: ['sucralose', 'splenda'],
    id: 'sucralose',
    name: 'Sucralose',
    plainEnglish: 'This is an artificial sweetener that keeps foods tasting sweet.',
    usedFor: 'Adds sweetness without regular sugar.',
    whyItMatters: 'Some shoppers look out for it in very processed snacks and drinks.',
  },
  {
    aliases: ['monosodium glutamate', 'msg', 'flavor enhancer 621'],
    id: 'msg',
    name: 'Monosodium Glutamate',
    plainEnglish: 'This boosts savory flavor so foods taste richer.',
    usedFor: 'Makes flavors taste stronger and more savory.',
    whyItMatters: 'It is safe for many people, but some still choose to limit it.',
  },
  {
    aliases: ['sodium nitrite', 'nitrite', 'e250', '250'],
    id: 'sodium-nitrite',
    name: 'Sodium Nitrite',
    plainEnglish: 'This helps preserved meats keep their color and last longer.',
    usedFor: 'Preserves cured meats and helps prevent spoilage.',
    whyItMatters: 'Many people watch for it in processed meats and try not to eat it often.',
  },
  {
    aliases: ['sodium nitrate', 'nitrate', 'e251', '251'],
    id: 'sodium-nitrate',
    name: 'Sodium Nitrate',
    plainEnglish: 'This is another preservative commonly used in cured meats.',
    usedFor: 'Helps preserve shelf life and color.',
    whyItMatters: 'It often shows up in heavily processed meat products.',
  },
  {
    aliases: [
      'artificial flavor',
      'artificial flavors',
      'artificial flavour',
      'artificial flavouring',
    ],
    id: 'artificial-flavors',
    name: 'Artificial Flavors',
    plainEnglish: 'This adds a designed flavor instead of coming straight from whole foods.',
    usedFor: 'Makes flavor more consistent and stronger.',
    whyItMatters: 'It can be a clue that the product is more processed.',
  },
  {
    aliases: [
      'artificial color',
      'artificial colors',
      'artificial colour',
      'red 40',
      'yellow 5',
      'yellow 6',
      'blue 1',
      'blue 2',
    ],
    id: 'artificial-colors',
    name: 'Artificial Colors',
    plainEnglish: 'This changes how the food looks more than how it nourishes you.',
    usedFor: 'Makes color brighter and more uniform.',
    whyItMatters: 'Some people prefer to avoid added dyes in everyday foods.',
  },
  {
    aliases: ['soy lecithin', 'lecithin', 'e322', '322'],
    id: 'soy-lecithin',
    name: 'Soy Lecithin',
    plainEnglish: 'This helps ingredients mix smoothly so the texture stays even.',
    usedFor: 'Keeps oils and water from separating.',
    whyItMatters: 'It is common in packaged foods, and some people avoid soy-based additives.',
  },
  {
    aliases: ['citric acid', 'e330', '330'],
    id: 'citric-acid',
    name: 'Citric Acid',
    plainEnglish: 'This adds tartness and helps foods stay fresh.',
    usedFor: 'Adjusts acidity and supports shelf life.',
    whyItMatters: 'It is very common and usually not a major concern on its own.',
  },
  {
    aliases: ['acetic acid', 'e260', '260'],
    id: 'acetic-acid',
    name: 'Acetic Acid',
    plainEnglish: 'This gives foods a sour note and helps control acidity.',
    usedFor: 'Balances acidity and supports preservation.',
    whyItMatters: 'It is common in sauces and pickled foods and is usually there for taste or shelf life.',
  },
  {
    aliases: ['xanthan gum', 'e415', '415'],
    id: 'xanthan-gum',
    name: 'Xanthan Gum',
    plainEnglish: 'This thickens food so it feels smoother and more stable.',
    usedFor: 'Improves texture and prevents separation.',
    whyItMatters: 'It is widely used, but some people prefer fewer texture additives.',
  },
  {
    aliases: ['guar gum', 'e412', '412'],
    id: 'guar-gum',
    name: 'Guar Gum',
    plainEnglish: 'This helps food stay thick and even.',
    usedFor: 'Improves texture and keeps ingredients from separating.',
    whyItMatters: 'It is common in packaged foods and is mostly there for texture.',
  },
  {
    aliases: ['carrageenan', 'e407', '407'],
    id: 'carrageenan',
    name: 'Carrageenan',
    plainEnglish: 'This is used to keep foods smooth and stable.',
    usedFor: 'Helps with texture in dairy and packaged products.',
    whyItMatters: 'Some people prefer to avoid it in heavily processed foods.',
  },
  {
    aliases: ['acetylated distarch adipate', 'modified starch', 'e1422', '1422'],
    id: 'acetylated-distarch-adipate',
    name: 'Acetylated Distarch Adipate',
    plainEnglish: 'This is a modified starch used to keep texture steady.',
    usedFor: 'Helps packaged foods stay thick and stable.',
    whyItMatters: 'It is mostly there for texture and is a sign of extra processing.',
  },
  {
    aliases: ['sodium benzoate', 'e211', '211'],
    id: 'sodium-benzoate',
    name: 'Sodium Benzoate',
    plainEnglish: 'This is a preservative used to help foods last longer.',
    usedFor: 'Helps prevent spoilage in packaged products.',
    whyItMatters: 'It is common in processed foods and drinks, so some people watch for it.',
  },
  {
    aliases: ['potassium sorbate', 'e202', '202'],
    id: 'potassium-sorbate',
    name: 'Potassium Sorbate',
    plainEnglish: 'This is a preservative that helps stop mold and spoilage.',
    usedFor: 'Extends shelf life in packaged foods.',
    whyItMatters: 'It is widely used, especially in products meant to last longer.',
  },
  {
    aliases: ['mono and diglycerides', 'mono- and diglycerides', 'e471', '471'],
    id: 'mono-and-diglycerides',
    name: 'Mono and Diglycerides',
    plainEnglish: 'These help oils and water stay mixed together.',
    usedFor: 'Improve texture and stop separation.',
    whyItMatters: 'They are common emulsifiers and usually show up in more processed foods.',
  },
  {
    aliases: ['preservative', 'preservatives', 'preservative added'],
    id: 'preservatives',
    name: 'Preservatives',
    plainEnglish: 'These help packaged foods last longer before spoiling.',
    usedFor: 'Extend shelf life and keep products stable in storage.',
    whyItMatters: 'They often appear in more processed foods, so some people like to keep an eye on them.',
  },
  {
    aliases: ['emulsifier', 'emulsifiers', 'emulsifying agent'],
    id: 'emulsifiers',
    name: 'Emulsifiers',
    plainEnglish: 'These help ingredients stay smoothly mixed instead of separating.',
    usedFor: 'Keep water and oil blended and improve texture.',
    whyItMatters: 'They are common in packaged foods and can be a sign of extra processing.',
  },
  {
    aliases: [
      'acidity regulator',
      'acidity regulators',
      'acid regulator',
      'acidity regulator 330',
    ],
    id: 'acidity-regulators',
    name: 'Acidity Regulators',
    plainEnglish: 'These control how sharp, tangy, or stable a food tastes.',
    usedFor: 'Balance acidity and help products stay consistent.',
    whyItMatters: 'They are usually there for taste or shelf stability, not nutrition.',
  },
  {
    aliases: [
      'stabilizer',
      'stabilizers',
      'stabiliser',
      'stabilisers',
      'stabliser',
      'stablisers',
    ],
    id: 'stabilizers',
    name: 'Stabilizers',
    plainEnglish: 'These help food keep the same texture over time.',
    usedFor: 'Stop products from separating, clumping, or changing texture.',
    whyItMatters: 'They are common in packaged foods, and some people prefer simpler ingredient lists.',
  },
  {
    aliases: ['water', 'drinking water', 'filtered water'],
    id: 'water',
    name: 'Water',
    plainEnglish: 'This is a basic ingredient used as a neutral base.',
    usedFor: 'Adds moisture and helps other ingredients mix.',
    whyItMatters: 'It is a simple everyday ingredient and usually not a concern by itself.',
  },
  {
    aliases: ['salt', 'sea salt', 'iodized salt', 'iodised salt'],
    id: 'salt',
    name: 'Salt',
    plainEnglish: 'This boosts flavor and helps preserve foods.',
    usedFor: 'Seasoning and shelf-life support.',
    whyItMatters: 'It is common and useful, but high amounts can add up quickly.',
  },
  {
    aliases: [
      'soybean oil',
      'soy bean oil',
      'soyabean oil',
      'soy oil',
      'refined soybean oil',
      'refined soyabean oil',
    ],
    id: 'soybean-oil',
    name: 'Soybean Oil',
    plainEnglish: 'This is a common cooking oil used in many packaged foods.',
    usedFor: 'Adds fat, helps frying, and improves texture.',
    whyItMatters: 'It is widely used, though some people prefer less refined oils or fewer added oils.',
  },
  {
    aliases: [
      'white pepper powder',
      'white pepper',
      'white pepper powdered',
      'ground white pepper',
    ],
    id: 'white-pepper',
    name: 'White Pepper',
    plainEnglish: 'This is a spice used to add mild heat and flavor.',
    usedFor: 'Seasoning and flavor.',
    whyItMatters: 'It is a simple kitchen spice and usually not a concern on its own.',
  },
];
